services:

  postgres-db-server:
    image: postgres
    container_name: postgres-db-server
    environment:
      - POSTGRES_USER=fiap
      - POSTGRES_PASSWORD=fiap123
      - POSTGRES_DB=todo-delivery
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  app-todo-delivery-service:
    container_name: app-todo-delivery-service
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres-db-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db-server:5432/todo-delivery
      - SPRING_DATASOURCE_USERNAME=fiap
      - SPRING_DATASOURCE_PASSWORD=fiap123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"